In [1]:
import numpy as np
import pandas as pd

# read in file

In [45]:
parent_folder = '/Users/mauriellenoto/Desktop/seager/uvphasedelay/data/'
trail = 'MokuLockInAmplifierData_20260629_143748'

In [29]:
def extract_info_and_data(parent_path, trial_name):
    import pandas as pd
    original_data_path = parent_path+trial_name

    # extract experiment info
    og_df = pd.read_csv(f"{original_data_path}.csv", skiprows=1)
    info_df = og_df[:8]
    info_df = info_df.T
    info_df.columns = info_df.iloc[0]
    info_df = info_df[1:]
    info_df.to_csv(parent_path+trial_name+"_info.csv")

    # create data df
    data_df = pd.read_csv(f"{original_data_path}.csv", header = 9)
    print(data_df)
    # data_df.to_csv(parent_path+trial_name+"_data.csv")
    # print(data_df)

    # print new csv file names

    filepaths = [parent_path+trial_name+"_info.csv", parent_path+trial_name+"_data.csv"]

    # print("experiment INFO saved to: \n", parent_path+trial_name+"_info.csv \n")
    # print("experiment DATA saved to: \n", parent_path+trial_name+"_data.csv")
    return filepaths


parent_folder = '/Users/mauriellenoto/Desktop/seager/uvphasedelay/data/'
trial = 'MokuLockInAmplifierData_20260629_143748'
data_and_info_paths = extract_info_and_data(parent_folder, trial)
info = pd.read_csv(data_and_info_paths[0])
data = pd.read_csv(data_and_info_paths[1])
data

       % Time (s)   Probe A (V)   Probe B (V)
0           0.000      0.173009     -0.004100
1           0.001      0.173009     -0.004100
2           0.002      0.173009     -0.004100
3           0.003      0.173009     -0.004133
4           0.004      0.173040     -0.004133
...           ...           ...           ...
59995      59.995      0.173009     -0.004133
59996      59.996      0.173009     -0.004167
59997      59.997      0.173009     -0.004133
59998      59.998      0.173009     -0.004167
59999      59.999      0.173040     -0.004133

[60000 rows x 3 columns]
experiment INFO saved to:
 /Users/mauriellenoto/Desktop/seager/uvphasedelay/data/MokuLockInAmplifierData_20260629_143748_info.csv

experiment DATA saved to:
 /Users/mauriellenoto/Desktop/seager/uvphasedelay/data/MokuLockInAmplifierData_20260629_143748_data.csv

       Unnamed: 0  % Time (s)   Probe A (V)   Probe B (V)
0               0       0.000      0.173009     -0.004100
1               1       0.001      0.173009     -0.004100
2               2       0.002      0.173009     -0.004100
3               3       0.003      0.173009     -0.004133
4               4       0.004      0.173040     -0.004133
...           ...         ...           ...           ...
59995       59995      59.995      0.173009     -0.004133
59996       59996      59.996      0.173009     -0.004167
59997       59997      59.997      0.173009     -0.004133
59998       59998      59.998      0.173009     -0.004167
59999       59999      59.999      0.173040     -0.004133

[60000 rows x 4 columns]

In [14]:
data_og = pd.read_csv(f'{parent_folder}/MokuLockInAmplifierData_20260629_143748.csv', skiprows=1)
header = data_og[:8]
header = header.T
header.columns = header.iloc[0]
header = header[1:]
header
# data_og.T

% Input 1,% Input 2,% Demodulation: Internal,% Lowpass filter corner frequency 1.00 MHz (time constant 159 ns),% Output 1 - I signal,% Output 2 - Demodulation signal,% Internal 10 MHz clock,% Acquired 2026-06-29 T 14:37:48 -0400,% Time (s)
DC,DC,50.000 000 000 kHz,slope 18 dB / octave,+0.0 dB gain,amplitude 500 mVpp,NaN,NaN,Probe A (V)
200 MHz,200 MHz,phase 0.000 000 deg,NaN,invert off,offset 750.0 mV,NaN,NaN,Probe B (V)
1 MOhm,1 MOhm,NaN,NaN,offset 0.000 0 V,output disabled,NaN,NaN,NaN
0 dB,0 dB,NaN,NaN,output disabled,NaN,NaN,NaN,NaN
1 Vpp,1 Vpp,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
data_df = pd.read_csv('/Users/mauriellenoto/Desktop/seager/uvphasedelay/data/MokuLockInAmplifierData_20260629_143748.csv', 
                      header =9
                      )
data_df
# new = data_df[:10]
# new

       % Time (s)   Probe A (V)   Probe B (V)
0           0.000      0.173009     -0.004100
1           0.001      0.173009     -0.004100
2           0.002      0.173009     -0.004100
3           0.003      0.173009     -0.004133
4           0.004      0.173040     -0.004133
...           ...           ...           ...
59995      59.995      0.173009     -0.004133
59996      59.996      0.173009     -0.004167
59997      59.997      0.173009     -0.004133
59998      59.998      0.173009     -0.004167
59999      59.999      0.173040     -0.004133

[60000 rows x 3 columns]